# Set Antigen for plugins
source $HOME/antigen.zsh
antigen init ~/.antigenrc

# FZF
export FZF_DEFAULT_COMMAND='fd --type f'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Vi-Mode in Terminal
bindkey -v
set -o vi
export EDITOR='nvim'

# Docker Plugin Completion
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes
zstyle ':completion:*' completer _extensions _complete _approximate

bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-up-line-or-history
bindkey -M menuselect 'k' vi-down-line-history
bindkey -M menuselect 'l' vi-forward-char

# Port in Completions
fpath+=${ZDOTDIR:-~}/.zsh_completions

# Source in custom config
if [ -f ~/.zsh_config ]; then
  source ~/.zsh_config
fi

# Port in Aliases
if [ -f ~/.zsh_aliases ]; then
  source ~/.zsh_aliases
else
  echo "You're missing the aliases"
fi

# Port in Functions
if [ -f ~/.zsh_functions ]; then
  source ~/.zsh_functions
else
  echo "You're missing the functions"
fi

if [ -f ~/.vaultrc ]; then
  source ~/.vaultrc
fi

if command -v pyenv 1>/dev/null 2>&1
then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
eval "$(direnv hook zsh)"

# Use Zoxide if it's executable
if command -v z > /dev/null 2>&1; then
  alias cd=z
fi

if command -v exa > /dev/null 2>&1; then
  alias ls=exa
fi

if [ -f ~/.custom_env ]; then
  source ~/.custom_env
fi

if [ -f ~/.custom_rc ]; then
  source ~/.custom_rc
fi

if [ -f ~/.aliases ]; then
  source ~/.aliases
fi

if [ -f ~/.functions ]; then
  source ~/.functions
fi

# LazyGit and Neovim
if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
  alias nvim=nvr -cc split --remote-wait +'set bufhidden=wipe'
  export VISUAL="nvr -cc split --remote-wait +'set bufhidden=wipe'"
  export EDITOR="nvr -cc split --remote-wait +'set bufhidden=wipe'"
else
  export VISUAL="nvim"
  export EDITOR="nvim"
fi
