(("default" . ((user-emacs-directory . "~/.config/doom-emacs")))
 ("doom" . ((user-emacs-directory . "~/.config/doom-emacs")
            (env . (("DOOMDIR" . "~/.config/doom-emacs")))))
 ("custom" . ((user-emacs-directory . "~/.config/custom-emacs")))
 ("vanilla" . ((user-emacs-directory . "~/.config/vanillamacs"))))
